---
version: 2
jobs:
  build:
    docker:
      - image: dealerdirect/php:5.6
    working_directory: ~/working_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            #> fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies with composer
          command: |-
            composer install --prefer-dist --no-progress --no-suggest --verbose --no-interaction
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - run:
          name: Lint PHP files
          command: parallel-lint --exclude vendor .
      - run:
          name: Validate Composer file
          command: composer validate
      - run:
          name: PHP Code Sniffer -- PSR2
          command: |-
              phpcs -p -s                                                       \
                  --encoding=utf8                                               \
                  --extensions=php                                              \
                  --ignore="vendor"                                             \
                  --report-full                                                 \
                  --report-gitblame                                             \
                  --standard=PSR2                                               \
                  ./ || true
      - run:
          name: Security checker
          command: security-checker -n security:check
      - run: |
          if [ -f ./vendor/bin/phpunit ]; then
             ./vendor/bin/phpunit -c phpunit.xml.dist
          else
            phpunit -c phpunit.xml.dist
          fi

# EOF
